import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import type { Metadata } from "next";
import {
  getAllProducts,
  getProductBySlug,
} from "@/modules/catalog/repository";
import { formatPrice } from "@/modules/catalog/domain/product";
import {
  ProductTabs,
  type ProductTab,
} from "@/modules/catalog/components/product-tabs";
import { AddToCartButton } from "@/modules/cart/add-to-cart-button";

// Pre-render a static page per product at build time.
export async function generateStaticParams() {
  const products = await getAllProducts();
  return products.map((product) => ({ slug: product.slug }));
}

// `PageProps<'/products/[slug]'>` is a globally-available helper generated by
// Next.js typegen — it types `params`/`searchParams` from the route literal.
export async function generateMetadata(
  props: PageProps<"/products/[slug]">,
): Promise<Metadata> {
  const { slug } = await props.params;
  const product = await getProductBySlug(slug);
  if (!product) return {};
  return { title: product.name, description: product.description };
}

export default async function ProductPage(props: PageProps<"/products/[slug]">) {
  // params and searchParams are Promises in this version — await them.
  const { slug } = await props.params;
  const { tab } = await props.searchParams;

  const product = await getProductBySlug(slug);
  if (!product) {
    notFound();
  }

  const activeTab: ProductTab =
    tab === "specifications" ? "specifications" : "description";

  return (
    <article className="flex flex-col gap-8">
      <Link
        href="/"
        className="text-sm text-muted transition hover:text-ink"
      >
        ← Retour à la boutique
      </Link>

      <div className="grid grid-cols-1 gap-10 md:grid-cols-2">
        <div className="relative aspect-square overflow-hidden rounded-3xl border border-line bg-paper">
          <Image
            src={product.image}
            alt={product.name}
            fill
            priority
            sizes="(max-width: 768px) 100vw, 480px"
            className="object-cover"
          />
        </div>

        <div className="flex flex-col gap-4">
          <span className="text-xs uppercase tracking-wide text-muted">
            {product.category}
          </span>
          <h1 className="text-3xl font-semibold text-ink">{product.name}</h1>
          <p className="text-2xl font-semibold text-gold-dark">
            {formatPrice(product.price)}
          </p>
          <p className="leading-relaxed text-ink/80">{product.description}</p>
          <div className="pt-2">
            <AddToCartButton
              product={{
                id: product.id,
                slug: product.slug,
                name: product.name,
                priceCents: product.price.amountCents,
                currency: product.price.currency,
                image: product.image,
              }}
            />
          </div>
        </div>
      </div>

      <ProductTabs product={product} active={activeTab} />
    </article>
  );
}
